### ISSUE TITLE
Mutable Map - access by pointer

### ISSUE THREAD

**Issue by heX16** [benibela/hamt#1]
Example:

``` pascal
  TMapItem = record
     a,b,c,d: integer;
     data: array [0..30000] of word;
  end; 

type TMutableMapStringString = specialize TMutableMap<string, TMapItem, THAMTTypeInfo>;

map['test'].a := 1; // Error: Argument cannot be assigned to
map['test'].data[1000] := 1; // Error: Argument cannot be assigned to

```

Need property '**mutable**'. See [gvector](https://github.com/graemeg/freepascal/blob/03c3db92824e74e579116d1efc4b626422d27691/packages/fcl-stl/src/gvector.pp#L76).

``` pascal
map.mutable['test']^.a := 1;
```

**Comment by benibela** [comment]
I have added it: fa3180d7acffd467403b59de6bfeadc054bc51db


Is a mutable property better than a default property on a distinct class like  I did it for [my vectors ](https://github.com/benibela/bbutils/blob/master/bbutils.pas#L587-L619)?

**Comment by heX16** [comment]
I believe that a mutable property should be the default in templates.
There are many situations when direct access to memory is required (for example: for convenience, for speed, or because of the requirements of an external API).

There are few situations where direct access needs to be prohibited (for example: "thread safe list"). The ban can easily be added by the user himself.

**Comment by heX16** [comment]
> I have added it: [fa3180d](https://github.com/benibela/hamt/commit/fa3180d7acffd467403b59de6bfeadc054bc51db)

P.S. Thank you! I will try to use this method soon.
